/**
 * T-008 — SOUL §12 twelve new v1 techniques.
 * Merged into `SKILLS`. None belong in academy/starter kits.
 */

import {
  ActionType,
  AttackMethod,
  CardRole,
  Clan,
  CombatRange,
  CombatTrigger,
  DamageProperty,
  DamageType,
  EffectType,
  ElementType,
  MarkConsumeTiming,
  PrimaryStat,
  Skill,
  SkillTag,
  SkillTier,
} from '../types';
import { defaultBaseWeight } from '../systems/CardContractSystem';

export const V1_UNIVERSAL_SKILL_IDS = [
  'tactical_scroll_rehearsal',
  'chakra_control_drill',
  'wire_kunai_reel',
  'explosive_kunai_blastback',
  'backstep_shuriken',
  'sealing_tag_chakra_lock',
  'tripwire_perimeter',
] as const;

export const V1_CLAN_SKILL_IDS = [
  'sharingan_3',
  'uzumaki_barrage',
  'twin_lion_fists',
  'morning_peacock',
  'mind_reading',
] as const;

export const V1_NEW_TECHNIQUE_IDS = [
  ...V1_UNIVERSAL_SKILL_IDS,
  ...V1_CLAN_SKILL_IDS,
] as const;

export const V1_NEW_TECHNIQUE_NAMES: readonly string[] = [
  'Tactical Scroll: Rehearsal',
  'Chakra Control Drill',
  'Wire Kunai: Reel In',
  'Explosive Kunai: Blastback',
  'Backstep Shuriken',
  'Sealing Tag: Chakra Lock',
  'Tripwire Perimeter',
  'Sharingan 3-Tomoe',
  'Uzumaki Barrage',
  'Gentle Step: Twin Lion Fists',
  'Morning Peacock',
  'Mind Reading Technique',
];

const weight = defaultBaseWeight();

export const SKILLS_COMBAT_V1_NEW: Record<string, Skill> = {
  TACTICAL_SCROLL_REHEARSAL: {
    id: 'tactical_scroll_rehearsal',
    name: 'Tactical Scroll: Rehearsal',
    tier: SkillTier.BASIC,
    description:
      'Choose a loadout tag and Discover 3 techniques with that tag (current weights). Source card frees its hand slot.',
    actionType: ActionType.ACTIVE,
    cardRole: CardRole.SUPPORT,
    tags: [SkillTag.DISCOVER, SkillTag.TOOL],
    baseWeight: weight,
    discover: { count: 3 },
    apCost: 1,
    chakraCost: 0,
    hpCost: 0,
    cooldown: 5,
    currentCooldown: 0,
    baseDamage: 0,
    scalingPerPoint: 0,
    scalingStat: PrimaryStat.INTELLIGENCE,
    damageType: DamageType.MENTAL,
    damageProperty: DamageProperty.NORMAL,
    attackMethod: AttackMethod.AUTO,
    element: ElementType.MENTAL,
    allowedRanges: [CombatRange.CLOSE, CombatRange.MEDIUM, CombatRange.LONG],
  },

  CHAKRA_CONTROL_DRILL: {
    id: 'chakra_control_drill',
    name: 'Chakra Control Drill',
    tier: SkillTier.BASIC,
    description:
      'Restore 4 chakra. Main Attack weight +2 on the next draw. Does not waive AP, HP, or cooldown.',
    actionType: ActionType.ACTIVE,
    cardRole: CardRole.SUPPORT,
    tags: [SkillTag.NINJUTSU],
    baseWeight: weight,
    apCost: 1,
    chakraCost: 0,
    hpCost: 0,
    cooldown: 3,
    currentCooldown: 0,
    baseDamage: 0,
    scalingPerPoint: 0,
    scalingStat: PrimaryStat.CHAKRA,
    damageType: DamageType.ELEMENTAL,
    damageProperty: DamageProperty.NORMAL,
    attackMethod: AttackMethod.AUTO,
    element: ElementType.PHYSICAL,
    allowedRanges: [CombatRange.CLOSE, CombatRange.MEDIUM, CombatRange.LONG],
    effects: [{ type: EffectType.CHAKRA_REGEN, value: 4, duration: 1, chance: 1 }],
  },

  WIRE_KUNAI_REEL: {
    id: 'wire_kunai_reel',
    name: 'Wire Kunai: Reel In',
    tier: SkillTier.BASIC,
    description:
      '6 damage at MEDIUM or LONG. PULL the foe 1 band. Apply Off-Balance: +20% to the next Attack (honest mark, not a hidden runtime %).',
    actionType: ActionType.ACTIVE,
    cardRole: CardRole.SIDE_ATTACK,
    tags: [SkillTag.TOOL, SkillTag.WEAPON, SkillTag.MARK],
    baseWeight: weight,
    apCost: 1,
    chakraCost: 0,
    hpCost: 0,
    cooldown: 2,
    currentCooldown: 0,
    baseDamage: 6,
    hitCount: 1,
    scalingPerPoint: 2,
    scalingStat: PrimaryStat.ACCURACY,
    damageType: DamageType.PHYSICAL,
    damageProperty: DamageProperty.NORMAL,
    attackMethod: AttackMethod.RANGED,
    element: ElementType.PHYSICAL,
    allowedRanges: [CombatRange.MEDIUM, CombatRange.LONG],
    markEffects: [
      { id: 'off_balance', duration: 1, stacks: 1, consume: MarkConsumeTiming.ATTEMPT },
    ],
    bandMove: { kind: 'PULL', steps: 1 },
  },

  EXPLOSIVE_KUNAI_BLASTBACK: {
    id: 'explosive_kunai_blastback',
    name: 'Explosive Kunai: Blastback',
    tier: SkillTier.ADVANCED,
    description:
      '7 damage at CLOSE or MEDIUM. PUSH the foe 1 band. Apply Exposed: +15% to the next ranged Attack.',
    actionType: ActionType.ACTIVE,
    cardRole: CardRole.SIDE_ATTACK,
    tags: [SkillTag.TOOL, SkillTag.WEAPON, SkillTag.MARK],
    baseWeight: weight,
    apCost: 1,
    chakraCost: 1,
    hpCost: 0,
    cooldown: 3,
    currentCooldown: 0,
    baseDamage: 7,
    hitCount: 1,
    scalingPerPoint: 2,
    scalingStat: PrimaryStat.DEXTERITY,
    damageType: DamageType.PHYSICAL,
    damageProperty: DamageProperty.NORMAL,
    attackMethod: AttackMethod.RANGED,
    element: ElementType.FIRE,
    allowedRanges: [CombatRange.CLOSE, CombatRange.MEDIUM],
    markEffects: [
      { id: 'exposed', duration: 1, stacks: 1, consume: MarkConsumeTiming.ATTEMPT },
    ],
    bandMove: { kind: 'PUSH', steps: 1 },
  },

  BACKSTEP_SHURIKEN: {
    id: 'backstep_shuriken',
    name: 'Backstep Shuriken',
    tier: SkillTier.BASIC,
    description:
      '5 damage. After the attempt the user retreats 1 band (does not spend the voluntary move).',
    actionType: ActionType.ACTIVE,
    cardRole: CardRole.SIDE_ATTACK,
    tags: [SkillTag.TOOL, SkillTag.WEAPON],
    baseWeight: weight,
    apCost: 1,
    chakraCost: 0,
    hpCost: 0,
    cooldown: 2,
    currentCooldown: 0,
    baseDamage: 5,
    hitCount: 1,
    scalingPerPoint: 2,
    scalingStat: PrimaryStat.ACCURACY,
    damageType: DamageType.PHYSICAL,
    damageProperty: DamageProperty.NORMAL,
    attackMethod: AttackMethod.RANGED,
    element: ElementType.PHYSICAL,
    allowedRanges: [CombatRange.CLOSE, CombatRange.MEDIUM, CombatRange.LONG],
    bandMove: { kind: 'SELF_RETREAT', steps: 1 },
  },

  SEALING_TAG_CHAKRA_LOCK: {
    id: 'sealing_tag_chakra_lock',
    name: 'Sealing Tag: Chakra Lock',
    tier: SkillTier.ADVANCED,
    description:
      'Drain 1 charge from the enemy priority Mode. If no Mode is ON, apply Silence 1 instead.',
    actionType: ActionType.ACTIVE,
    cardRole: CardRole.SUPPORT,
    tags: [SkillTag.NINJUTSU, SkillTag.MARK],
    baseWeight: weight,
    apCost: 2,
    chakraCost: 4,
    hpCost: 0,
    cooldown: 6,
    currentCooldown: 0,
    baseDamage: 0,
    scalingPerPoint: 0,
    scalingStat: PrimaryStat.INTELLIGENCE,
    damageType: DamageType.MENTAL,
    damageProperty: DamageProperty.NORMAL,
    attackMethod: AttackMethod.AUTO,
    element: ElementType.MENTAL,
    allowedRanges: [CombatRange.CLOSE, CombatRange.MEDIUM, CombatRange.LONG],
    modeInteraction: { consumeCharges: 1 },
  },

  TRIPWIRE_PERIMETER: {
    id: 'tripwire_perimeter',
    name: 'Tripwire Perimeter',
    tier: SkillTier.ADVANCED,
    description:
      'Place a Reaction Mark (duration 2): the first real enemy band change deals 8 damage and 60% Stun 1. No reaction if the band does not change.',
    actionType: ActionType.ACTIVE,
    cardRole: CardRole.SUPPORT,
    tags: [SkillTag.TOOL, SkillTag.MARK],
    baseWeight: weight,
    apCost: 1,
    chakraCost: 0,
    hpCost: 0,
    cooldown: 4,
    currentCooldown: 0,
    baseDamage: 0,
    scalingPerPoint: 0,
    scalingStat: PrimaryStat.DEXTERITY,
    damageType: DamageType.PHYSICAL,
    damageProperty: DamageProperty.NORMAL,
    attackMethod: AttackMethod.AUTO,
    element: ElementType.PHYSICAL,
    allowedRanges: [CombatRange.CLOSE, CombatRange.MEDIUM, CombatRange.LONG],
    markEffects: [
      {
        id: 'tripwire',
        duration: 2,
        stacks: 1,
        consume: MarkConsumeTiming.NONE,
        trigger: CombatTrigger.ON_MOVE,
      },
    ],
  },

  SHARINGAN_3TOMOE: {
    id: 'sharingan_3',
    name: 'Sharingan 3-Tomoe',
    tier: SkillTier.ADVANCED,
    description:
      'Combat Mode: 3 charges. Activation 3 AP + 6 CP; upkeep 6 CP; CD 5. Lightning/Chidori routes; lateral from Sharingan 2-Tomoe transfers charges without refill. Range checked only on activate.',
    actionType: ActionType.TOGGLE,
    cardRole: CardRole.MODE,
    tags: [SkillTag.MODE, SkillTag.NINJUTSU, SkillTag.UCHIHA, SkillTag.FIRE],
    baseWeight: weight,
    apCost: 3,
    chakraCost: 6,
    hpCost: 0,
    cooldown: 5,
    currentCooldown: 0,
    baseDamage: 0,
    scalingPerPoint: 0,
    scalingStat: PrimaryStat.INTELLIGENCE,
    damageType: DamageType.ELEMENTAL,
    damageProperty: DamageProperty.NORMAL,
    attackMethod: AttackMethod.AUTO,
    element: ElementType.LIGHTNING,
    isToggle: true,
    upkeepCost: 6,
    modeInteraction: { modeId: 'sharingan_3', family: 'SHARINGAN' },
    requirements: {
      stats: { [PrimaryStat.INTELLIGENCE]: 3, [PrimaryStat.CALMNESS]: 2 },
      clan: Clan.UCHIHA,
    },
  },

  UZUMAKI_BARRAGE: {
    id: 'uzumaki_barrage',
    name: 'Uzumaki Barrage',
    tier: SkillTier.ADVANCED,
    description:
      '3×4 hits. With Shadow Clones ON: spend 1 charge (red) and gain +2 hits. Charge spend is visible; clones do not die from attacking.',
    actionType: ActionType.ACTIVE,
    cardRole: CardRole.SIDE_ATTACK,
    tags: [SkillTag.TAIJUTSU, SkillTag.MULTI_HIT, SkillTag.UZUMAKI],
    baseWeight: weight,
    apCost: 2,
    chakraCost: 0,
    hpCost: 0,
    cooldown: 3,
    currentCooldown: 0,
    baseDamage: 4,
    hitCount: 3,
    scalingPerPoint: 1,
    scalingStat: PrimaryStat.STRENGTH,
    damageType: DamageType.PHYSICAL,
    damageProperty: DamageProperty.NORMAL,
    attackMethod: AttackMethod.MELEE,
    element: ElementType.PHYSICAL,
    allowedRanges: [CombatRange.CLOSE],
    modeInteraction: {
      modeId: 'shadow_clone',
      family: 'CLONES',
      consumeCharges: 1,
      bonusHits: 2,
    },
    requirements: { clan: Clan.UZUMAKI },
  },

  TWIN_LION_FISTS: {
    id: 'twin_lion_fists',
    name: 'Gentle Step: Twin Lion Fists',
    tier: SkillTier.HIDDEN,
    description:
      '2×9. With Byakugan ON and a Chakra Point mark: +50% damage, 30% pen, consume the mark on impact. Miss preserves enemy marks.',
    actionType: ActionType.ACTIVE,
    cardRole: CardRole.ATTACK,
    tags: [SkillTag.TAIJUTSU, SkillTag.MULTI_HIT, SkillTag.HYUGA, SkillTag.MARK],
    baseWeight: weight,
    apCost: 4,
    chakraCost: 9,
    hpCost: 0,
    cooldown: 5,
    currentCooldown: 0,
    baseDamage: 9,
    hitCount: 2,
    scalingPerPoint: 3,
    scalingStat: PrimaryStat.ACCURACY,
    damageType: DamageType.PHYSICAL,
    damageProperty: DamageProperty.PIERCING,
    attackMethod: AttackMethod.MELEE,
    element: ElementType.PHYSICAL,
    penetration: 0.3,
    allowedRanges: [CombatRange.CLOSE],
    modeInteraction: {
      modeId: 'byakugan',
      family: 'HYUGA',
      requireMarkId: 'chakra_point',
      damageMultBonus: 0.5,
    },
    requirements: {
      stats: { [PrimaryStat.ACCURACY]: 3 },
      clan: Clan.HYUGA,
    },
  },

  MORNING_PEACOCK: {
    id: 'morning_peacock',
    name: 'Morning Peacock',
    tier: SkillTier.FORBIDDEN,
    description:
      '6×4. Requires Gate of Limit ON. +15% per remaining charge; consume all charges and close the Gate on play.',
    actionType: ActionType.ACTIVE,
    cardRole: CardRole.ATTACK,
    tags: [SkillTag.TAIJUTSU, SkillTag.MULTI_HIT, SkillTag.LEE],
    baseWeight: weight,
    apCost: 5,
    chakraCost: 0,
    hpCost: 10,
    cooldown: 7,
    currentCooldown: 0,
    baseDamage: 4,
    hitCount: 6,
    scalingPerPoint: 2,
    scalingStat: PrimaryStat.STRENGTH,
    damageType: DamageType.PHYSICAL,
    damageProperty: DamageProperty.NORMAL,
    attackMethod: AttackMethod.MELEE,
    element: ElementType.FIRE,
    allowedRanges: [CombatRange.CLOSE],
    modeInteraction: {
      modeId: 'gate_of_limit',
      family: 'GATES',
      requireOn: true,
      consumeCharges: 4,
      consumeAllCharges: true,
      damagePerChargeBonus: 0.15,
    },
    requirements: {
      stats: { [PrimaryStat.STRENGTH]: 4, [PrimaryStat.SPEED]: 4 },
      clan: Clan.LEE,
    },
  },

  MIND_READING: {
    id: 'mind_reading',
    name: 'Mind Reading Technique',
    tier: SkillTier.ADVANCED,
    description:
      'Read full enemy intent. Discover 3 MENTAL techniques (current weights). No Mode required.',
    actionType: ActionType.ACTIVE,
    cardRole: CardRole.SUPPORT,
    tags: [SkillTag.GENJUTSU, SkillTag.DISCOVER, SkillTag.YAMANAKA, SkillTag.MENTAL],
    baseWeight: weight,
    discover: { count: 3, tag: SkillTag.MENTAL },
    apCost: 1,
    chakraCost: 4,
    hpCost: 0,
    cooldown: 4,
    currentCooldown: 0,
    baseDamage: 0,
    scalingPerPoint: 0,
    scalingStat: PrimaryStat.INTELLIGENCE,
    damageType: DamageType.MENTAL,
    damageProperty: DamageProperty.NORMAL,
    attackMethod: AttackMethod.AUTO,
    element: ElementType.MENTAL,
    allowedRanges: [CombatRange.CLOSE, CombatRange.MEDIUM, CombatRange.LONG],
    requirements: { clan: Clan.YAMANAKA },
  },
};
